name: Debug

on: 
  push:
  pull_request:
    branches:
      - '!main'

env:
  DOTNET_VERSION: '6.0.100'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: InsanityBot
        path: InsanityBot/bin/Debug/net5.0/